"""empty message

Revision ID: 911156ed374c
Revises: 
Create Date: 2024-08-13 12:25:16.719419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911156ed374c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('board', sa.JSON(), nullable=False),
    sa.Column('move_player', sa.String(length=10), nullable=False),
    sa.Column('start_row', sa.Integer(), nullable=False),
    sa.Column('start_col', sa.Integer(), nullable=False),
    sa.Column('end_row', sa.Integer(), nullable=False),
    sa.Column('end_col', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('player')
    # ### end Alembic commands ###
