"""empty message

Revision ID: a229878a40e1
Revises: 69bcac74f3a7
Create Date: 2024-08-02 18:46:31.994893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a229878a40e1'
down_revision = '69bcac74f3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('start_row', sa.Integer(), nullable=False),
    sa.Column('start_col', sa.Integer(), nullable=False),
    sa.Column('end_row', sa.Integer(), nullable=False),
    sa.Column('end_col', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('move')
    # ### end Alembic commands ###
